name: 'Renew'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
#     - cron: '25 17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: macos-latest

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: 'Update Chrome'           
          run: |
            brew reinstall --cask google-chrome

        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            
        - name: 'Renew'
          env:
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            USER_ID_2: ${{ secrets.USER_ID_2 }}
            PASS_WD_2: ${{ secrets.PASS_WD_2 }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 main-w.py.

