name: V2EX-Checkin
on:
    workflow_dispatch:
    schedule:
        - cron: "0 00 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "Checkin"
              run: |
                  node V2EX/v2ex.js
              env:
                  V2EXCK: ${{ secrets.V2EXCK }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}